#!/bin/bash
# Reads in the index.html and data.json
# file and 'pre-renders' the HTML page
# so that this doesnt depend on the user
# having javascript enabled
#
# on my server I do: ./ssg && mv static.html index.html
#
# requires: jq

generate_html() {
	# parse JSON line delimited info
	IDS="$(jq -r 'keys[]' -r <data.json | sort -n)"
	while IFS= read -r id; do
		# read value from JSON
		blob="$(jq -r ".\"${id}\"" -r <data.json)"
		img_url="$(jq -r '.img_url' -r <<<"${blob}")"
		alt_text="$(jq -r '.alt_text' -r <<<"${blob}")"
		printf '<figure class="p-2 text-center"><a href="%s" rel="noreferrer"><img src="%s" alt="xkcd %d"></a><figcaption><a class="mt-1 badge badge-pill" href="https://xkcd.com/%d">https://xkcd.com/%d</a></figcaption><div class="mt-1 caption">%s</div></figure>\n' \
			"${img_url}" \
			"${img_url}" \
			"${id}" \
			"${id}" \
			"${id}" \
			"${alt_text}"
	done <<<"${IDS}"
}

while IFS= read -r line; do
	if [[ "${line}" == *"noscript"* ]]; then
		# replace the noscript line with a
		# pre-rendered page
		generate_html
	elif [[ "${line}" == *"<script"* ]] && [[ "${line}" != *"back-arrow-bundle"* ]]; then
		# do nothing, remove javascript lines
		: # noop
	else
		echo "${line}"
	fi
done <./index.html >./static.html
